# Generated by Django 5.2.7 on 2025-10-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='view_library',
            field=models.BooleanField(default=True),
        ),
    ]
