# Generated by Django 5.2.7 on 2025-10-23 14:47

import apps.positions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_company_view_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Position Category',
                'verbose_name_plural': 'Position Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('formula', models.CharField(help_text='Example: age > 20', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, default=apps.positions.models.get_default_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('expected_hiring_date', models.DateField(blank=True, null=True)),
                ('number_to_hire', models.PositiveIntegerField(default=1)),
                ('number_to_shortlist', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('is_library', models.BooleanField(default=False, help_text='If true, this position is a reusable template (library).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, default=apps.positions.models.get_default_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='positions.positioncategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positions.condition')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positioncondition_set', to='positions.position')),
            ],
            options={
                'unique_together': {('position', 'condition')},
            },
        ),
        migrations.AddField(
            model_name='position',
            name='conditions',
            field=models.ManyToManyField(blank=True, related_name='positions', through='positions.PositionCondition', to='positions.condition'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hard', 'Hard Skill'), ('soft', 'Soft Skill')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, default=apps.positions.models.get_default_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='PositionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=3)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionskill_set', to='positions.position')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positions.skill')),
            ],
            options={
                'unique_together': {('position', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='position',
            name='skills',
            field=models.ManyToManyField(related_name='positions', through='positions.PositionSkill', to='positions.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('company', 'name')},
        ),
    ]
