# Generated by Django 5.2.7 on 2025-10-24 22:08

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('idle', 'Idle')], default='idle', help_text='Status of the embedding process.', max_length=20),
        ),
        migrations.AddField(
            model_name='position',
            name='last_embedding_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
