# Generated by Django 5.2.7 on 2025-10-22 14:13

import apps.documents.models
import apps.documents.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=apps.documents.storage.CompanyStorage(), upload_to=apps.documents.models.company_storage_path)),
                ('pdf_preview', models.FileField(blank=True, help_text='Generated PDF preview for visualization.', null=True, storage=apps.documents.storage.CompanyStorage(), upload_to=apps.documents.models.company_storage_path)),
                ('filename', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word / Docx'), ('other', 'Other')], default='other', max_length=20)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('email', 'Email'), ('app', 'App'), ('other', 'Other')], default='upload', max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_progress', models.PositiveSmallIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('processing_result', models.CharField(blank=True, help_text='Empty if success, or error message if failed.', max_length=500, null=True)),
                ('candidate', models.ForeignKey(blank=True, help_text='Candidate this document belongs to (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='candidates.candidate')),
                ('company', models.ForeignKey(help_text='Company that owns this document.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.company')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded or created this document.', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
