# Generated by Django 5.2.7 on 2025-10-22 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone1', models.CharField(blank=True, max_length=50)),
                ('phone2', models.CharField(blank=True, max_length=50)),
                ('email1', models.EmailField(blank=True, max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Owning company (multi-tenant isolation).', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='accounts.company')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('jek', 'Jek'), ('upload', 'Upload'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='jek', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidates.candidate')),
                ('company', models.ForeignKey(help_text='Company that sourced the resume.', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
