# Generated by Django 5.2.7 on 2025-10-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Source file if this résumé was uploaded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='documents.document'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('company', 'email1')},
        ),
    ]
