# Generated by Django 5.2.7 on 2025-10-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='schema_version',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
