# Generated by Django 5.2.7 on 2025-10-24 10:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_resume_schema_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='OpenAI text-embedding-3-small vector', null=True),
        ),
    ]
