# Generated by Django 5.2.7 on 2025-10-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_resume_embedding'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS resume_embedding_cosine_idx
            ON candidates_resume
            USING ivfflat (embedding vector_cosine_ops)
            WITH (lists = 100);
            """,
            reverse_sql="DROP INDEX IF EXISTS resume_embedding_cosine_idx;"
        ),
    ]
