"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta


load_dotenv()
LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "DEBUG")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret")
DEBUG = os.getenv("DJANGO_DEBUG", 0)

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")


# Application definition
APPEND_SLASH = True
SIMPLE_JWT = {
    # Increase access token lifetime (example: 7 days)
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),

    # You can also adjust the refresh token lifetime (example: 30 days)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),

    # Optional: control whether the refresh token rotates or not
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,

    # Recommended defaults
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "rest_framework","rest_framework_simplejwt","rest_framework_simplejwt.token_blacklist", 
    "django_filters","drf_spectacular",
    "parler","corsheaders","channels","pgvector.django",


    'apps.public',
    'apps.accounts',
    'apps.documents',
    'apps.candidates',
    'apps.openaiapp',
    'apps.positions',
    'apps.matching',
    'apps.auth_custom',
    'apps.assessment',
    'apps.workflow',
    'apps.dashboard',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # must be before CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # "main.middleware.log_exceptions.LogBadRequestMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "main.context_processors.deploy_metadata",
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB","brain"),
        "USER": os.getenv("POSTGRES_USER","brain"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD","brain"),
        "HOST": os.getenv("POSTGRES_HOST","localhost"),
        "PORT": int(os.getenv("POSTGRES_PORT","5432")),
    }
}


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ]
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = "accounts.JekUser"

DEFAULT_COMPANIES = {
    "superuser": "jekjob",
    "candidate": "jenijob",
}


##emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# The host and port of the SMTP server
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
# The username and password of the SMTP account
EMAIL_HOST_USER = 'adnaneassist@gmail.com'
EMAIL_HOST_PASSWORD = 'gnop kzbn fzjf xzru'
# The security options for the SMTP connection
EMAIL_USE_TLS = True # Use TLS encryption
EMAIL_USE_SSL = False # Do not use SSL encryption
# The default from email address
DEFAULT_FROM_EMAIL = 'adnaneassist@gmail.com'


LANGUAGES = [
    ("fr","French"),("ar-tn","Tunisian")
]


LANGUAGE_CODE = os.getenv("DEFAULT_LANGUAGE","fr")

PARLER_LANGUAGES = {
    None: [{"code": code} for code, _ in LANGUAGES],
    "default": {"fallbacks": ["en"], "hide_untranslated": False},
}

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")



DEPLOY_COMMIT = os.getenv("DEPLOY_COMMIT", "")
DEPLOY_DATE = os.getenv("DEPLOY_DATE", "")
DEPLOY_AUTHOR = os.getenv("DEPLOY_AUTHOR", "")
DEPLOY_BRANCH = os.getenv("DEPLOY_BRANCH", "")
DEPLOY_MESSAGE = os.getenv("DEPLOY_MESSAGE", "")


# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "verbose": {
#             "format": "{asctime} | {levelname:<8} | {name} | {message} | {pathname}:{lineno}",
#             "style": "{",
#         },
#         "simple": {
#             "format": "{levelname} {message}",
#             "style": "{",
#         },
#     },
#     "handlers": {
#         "console": {
#             "class": "logging.StreamHandler",
#             "formatter": "verbose",
#         },
#         "file": {
#             "class": "logging.FileHandler",
#             "filename": BASE_DIR / "logs" / "django.log",
#             "formatter": "verbose",
#         },
#     },
#     "loggers": {
#         # Catch all Django logs
#         "django": {
#             "handlers": ["console", "file"],
#             "level": os.getenv("DJANGO_LOG_LEVEL", "DEBUG"),
#             "propagate": True,
#         },
#         # Application logs (you can add more per app)
#         "apps": {
#             "handlers": ["console", "file"],
#             "level": "DEBUG",
#             "propagate": False,
#         },
#     },
#     "root": {
#         "handlers": ["console", "file"],
#         "level": os.getenv("DJANGO_LOG_LEVEL", "DEBUG"),
#     }
# }

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
] or [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

STORAGE_ROOT = BASE_DIR / "storage"

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")


try:
    from .beat_schedule import CELERY_BEAT_SCHEDULE
except ImportError:
    CELERY_BEAT_SCHEDULE = {}