# Generated by Django 6.0.2 on 2026-06-09 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_company_access_jekjob_resumes_workplace'),
        ('candidates', '0005_add_resume_embedding_index'),
        ('positions', '0002_position_embedding_position_embedding_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('yesno', 'yesno'), ('single_choice', 'single_choice'), ('multi_choice', 'multi_choice'), ('rating', 'rating'), ('numeric', 'numeric'), ('text', 'text')], max_length=20)),
                ('difficulty', models.IntegerField(default=1)),
                ('expected_duration', models.IntegerField(default=60)),
                ('max_score', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('expected_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=0.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessment.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='assessment.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.quizcategory'),
        ),
        migrations.CreateModel(
            name='QuizCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='assessment.quizcategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.CharField(choices=[('skill', 'skill'), ('interview', 'interview'), ('satisfaction', 'satisfaction'), ('other', 'other')], default='skill', max_length=20)),
                ('language_mode', models.CharField(choices=[('flexible', 'flexible'), ('fixed', 'fixed')], default='fixed', max_length=20)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('category_mix_mode', models.CharField(choices=[('uniform', 'uniform'), ('weighted', 'weighted'), ('custom', 'custom')], default='uniform', max_length=20)),
                ('difficulty_mix_mode', models.CharField(choices=[('uniform', 'uniform'), ('progressive', 'progressive'), ('custom', 'custom')], default='uniform', max_length=20)),
                ('default_question_count', models.IntegerField(default=10)),
                ('is_library', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='positions.skill')),
            ],
        ),
        migrations.CreateModel(
            name='QuizInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_mode', models.CharField(choices=[('auto', 'auto'), ('flexible', 'flexible'), ('fixed', 'fixed')], default='auto', max_length=20)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('question_count', models.IntegerField(default=10)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.quiztemplate')),
            ],
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='assessment.quiztemplate'),
        ),
        migrations.AddField(
            model_name='question',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.quiztemplate'),
        ),
    ]
